[variables]
NIXPACKS_METADATA = "ruby"

[phases.setup]
nixPkgs = ["ruby_3_2", "nodejs", "yarn", "postgresql"]

[phases.install]
cmds = ["bundle install --without development test"]

[phases.build]
cmds = [
  "bundle exec rails assets:precompile"
]

[phases.start]
cmd = "./bin/railway-entrypoint rails server -b 0.0.0.0 -p $PORT -e production"