[variables]
NIXPACKS_METADATA = "ruby"

[phases.setup]
nixPkgs = ["ruby_3_2", "nodejs", "yarn"]

[phases.build]
cmds = [
  "bundle install",
  "bundle exec rails assets:precompile"
]

[phases.start]
cmd = "./bin/railway-entrypoint rails server -p $PORT -e production"
EOF < /dev/null