[build]
builder = "nixpacks"

[deploy]
startCommand = "./bin/railway-entrypoint rails server -p $PORT -e production"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3