[build]
builder = "nixpacks"

[deploy]
startCommand = "./bin/railway-entrypoint rails server -b 0.0.0.0 -p $PORT -e production"
healthcheckPath = "/ping"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5