databases:
  - name: mediedu-db
    databaseName: mediedu_production
    user: mediedu_user

services:
  - type: web
    name: mediedu-simple
    env: ruby
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails assets:clean
    startCommand: bundle exec rails db:create db:migrate db:seed && bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mediedu-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: SECRET_KEY_BASE
        generateValue: true