services:
  - type: web
    name: mediedu-simple
    env: ruby
    buildCommand: bundle install && rails assets:precompile && rails db:create && rails db:migrate && rails db:seed
    startCommand: rails server -p $PORT -e production
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
    autoDeploy: true
EOF < /dev/null